variables:
  COMPOSER_ALLOW_SUPERUSER: 1

stages:
  - build
  - code-quality

include:
  - template: Composer.gitlab-ci.yml


package_install:
  stage: build
  image: mallardduck/gitlab-ci-pipeline-php:8.1-alpine
  when: always
  script:
    - composer install --ignore-platform-reqs
  artifacts:
    paths:
      - .Build/

default:
  image: mallardduck/gitlab-ci-pipeline-php:8.1-alpine
  tags:
    - docker

create-extension:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress

php-lint:
  stage: code-quality
  needs:
    - package_install
  script:
    - composer run ci:php:lint

php-cs-fixer:
  stage: code-quality
  needs:
    - package_install
  script:
    - composer run ci:php:cs

php-stan:
  stage: code-quality
  needs:
    - package_install
  script:
    - composer run ci:php:stan
