services:
  GridElementsTeam\Gridelements\EventListener\ExtTablesInclusionPostProcessing:
    tags:
      - name: event.listener
        identifier: 'ext-table-inclusion-post-proc'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent
